# Generated by Django 4.2.4 on 2023-09-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_delete_signup1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField( max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
