# Generated by Django 4.2.4 on 2023-09-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_signup_admin_signup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
