# Generated by Django 4.2.4 on 2023-09-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_admin_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='addCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founder_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.charity_category')),
            ],
        ),
    ]
