# Generated by Django 4.2.4 on 2023-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_addcharity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcharity',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='addcharity',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
