# Generated by Django 4.2.4 on 2023-09-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_addcharity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='addCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founder_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='admin_Signup',
        ),
        migrations.RemoveField(
            model_name='addcharity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='addcampaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.campaign_category'),
        ),
    ]
