# Generated by Django 4.2.4 on 2023-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_addcampaign_email_alter_addcampaign_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcampaign',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
