# Generated by Django 4.2.4 on 2023-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_addcampaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcharity',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
