# Generated by Django 4.2.4 on 2023-12-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='name',
        ),
    ]
