# Generated by Django 4.2.4 on 2024-01-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_alter_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founder_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('amount', models.IntegerField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
