# Generated by Django 4.2.4 on 2024-01-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_setamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setamount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='setamount',
            name='founder_name',
        ),
        migrations.AddField(
            model_name='setamount',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_signup'),
        ),
        migrations.AlterField(
            model_name='setamount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcharity'),
        ),
    ]
