# Generated by Django 4.2.4 on 2024-01-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_remove_setamount_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setamount',
            name='user',
        ),
        migrations.AddField(
            model_name='setamount',
            name='charity_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcharity'),
        ),
        migrations.AlterField(
            model_name='setamount',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_signup'),
        ),
    ]
