# Generated by Django 4.2.4 on 2024-01-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_remove_setamount_user_setamount_charity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setamount',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
