# Generated by Django 4.2.4 on 2024-01-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_alter_setamount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setamount',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_signup'),
        ),
    ]
