# Generated by Django 4.2.4 on 2024-01-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_alter_setamount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setamount',
            name='campaign_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcampaign'),
        ),
    ]
