# Generated by Django 4.2.4 on 2024-01-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_alter_setamount_campaign_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetAmount',
        ),
    ]
