# Generated by Django 4.2.4 on 2024-01-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_delete_setamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetAmountCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('charity_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcharity')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_signup')),
            ],
        ),
        migrations.CreateModel(
            name='SetAmountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('campaign_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcampaign')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_signup')),
            ],
        ),
    ]
