# Generated by Django 4.2.4 on 2024-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_setamountcharity_setamountcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='setamountcampaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setamountcharity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
