# Generated by Django 4.2.4 on 2024-01-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_setamountcampaign_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autodedut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_signup')),
            ],
        ),
    ]
