# Generated by Django 4.2.4 on 2024-01-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_autodedut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autodedut',
            new_name='Autodeduct',
        ),
    ]
