# Generated by Django 4.2.4 on 2024-01-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setamountcampaign',
            name='campaign_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcampaign'),
        ),
    ]
