# Generated by Django 4.2.4 on 2024-01-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_alter_setamountcampaign_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcharity',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
