# Generated by Django 5.0.1 on 2024-01-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_signup',
            name='user_password',
        ),
    ]
