# Generated by Django 5.0.1 on 2024-01-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_remove_user_signup_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='somthing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
