# Generated by Django 5.0.1 on 2024-01-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_somthing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='somthing',
        ),
    ]
