# Generated by Django 5.0.1 on 2024-02-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_alter_user_signup_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(max_length=32),
        ),
    ]
