# Generated by Django 5.0.1 on 2024-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_alter_otp_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
