# Generated by Django 4.1.5 on 2024-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='email',
            field=models.EmailField(default='shamnasabdulla@gmail.com', max_length=254),
        ),
    ]
