# Generated by Django 4.1.5 on 2024-03-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_admin_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('otp_secret', models.CharField(max_length=32)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
