# Generated by Django 4.1.5 on 2024-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_adminotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_login',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
